name: Continuous Itregration

on:
  push:
    branches: [master]

jobs:
  Test push actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm test
