
name: CI

on:
  push:
    branches: 
      -master
  pull_request:
    branches: 
      -master
jobs:
  test:
    name: run tests
    runs-on: ubuntu-18.04
    steps: 
    - name: npm install and run tests
      run: 
        npm install
        npm run test

