name: Continuous Itregration

on:
  push:
    branches: [master]

jobs:
  Test-push-action:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "13"
      - run: npm install
      - run: npm test
